export const AGENTPROXY_RESPONSE_HEADERS = {
  cache: "X-AgentProxy-Cache",
  cacheHit: "X-AgentProxy-Cache-Hit",
  cacheLatency: "X-AgentProxy-Cache-Latency",
  compression: "X-AgentProxy-Compression",
  costSaved: "X-AgentProxy-Cost-Saved",
  decision: "X-AgentProxy-Decision",
  fallbackAttempts: "X-AgentProxy-Fallback-Attempts",
  latencyMs: "X-AgentProxy-Latency-Ms",
  model: "X-AgentProxy-Model",
  progress: "X-AgentProxy-Progress",
  provider: "X-AgentProxy-Provider",
  requestId: "X-AgentProxy-Request-Id",
  responseCost: "X-AgentProxy-Response-Cost",
  tokensIn: "X-AgentProxy-Tokens-In",
  tokensOut: "X-AgentProxy-Tokens-Out",
  tokensPerSecond: "X-AgentProxy-Tokens-Per-Second",
  version: "X-AgentProxy-Version",
} as const;
